### ISSUE TITLE
HELP?

### ISSUE THREAD

**Issue by fatboi615** [danielkrupinski/curiumcheat-csgo#1]
dont know what im doing wrong i just load it up and get this error so i cant compile
https://gyazo.com/d78fd4ca7045001c4ccdd99d188fd4e4 this is what i get

**Comment by danielkrupinski** [comment]
Make sure your build configuration is set to Release | x86

**Comment by fatboi615** [comment]
i am

**Comment by danielkrupinski** [comment]
Do you have visual studio 2017 and windows sdk?
