### ISSUE TITLE
still undetected 

### ISSUE THREAD

**Issue by anurag01021996** [danielkrupinski/curiumcheat-csgo#4]
i want to test this cheat...i want to know if its still undetected @danielkrupinski

**Comment by danielkrupinski** [comment]
I don't play CS:GO anymore but account I played on is not banned so I think it's undetected.

**Comment by anurag01021996** [comment]
I tested the cheat bro...it's working fine...but I can't figure out how to do bhop...I mean auto jump is working if I hold the space bar... But can't figure out how to do the strafing and shit ...please guide me a bit

**Comment by anurag01021996** [comment]
BTW cheat is awesome

**Comment by anurag01021996** [comment]
It's detected now :(

**Comment by danielkrupinski** [comment]
Did you get a VAC ban?

**Comment by anurag01021996** [comment]
yes

**Comment by anurag01021996** [comment]
but hopefully it was my fun account...didnt tried on main...duh :P

**Comment by danielkrupinski** [comment]
I played with this cheat on my main and I didn't get banned... When was your last game?

**Comment by anurag01021996** [comment]
4 days ago
